services:
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    container_name: wakapi
    ports:
      - "3000:3000"
    environment:
      - WAKAPI_PASSWORD_SALT=${WAKAPI_PASSWORD_SALT}
    volumes:
      - wakapi-data:/data

volumes:
  wakapi-data:
