name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Ensure Docker Daemon is Running
        run: |
          docker info || sudo service docker start
          sleep 10

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
