name: Generate Contribution Graphic

on:
  push: # Trigger the workflow on each commit
    branches:
      - main # or the branch you want to monitor
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib PyGithub

      - name: Run script
        run: python generate_graphic.py
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md contributions.png
          git commit -m 'Update contributions graphic'
          git push
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
